### ISSUE TITLE
组件除了第一次初始化，其他都是宽度100px

### ISSUE THREAD

**Issue by axy541877028** [surmon-china/vue-video-player#100]
您好，我设置组件width:100%此组件在第一次初始化的时候生效了，我用路由回退再次进入组件就一直是100px  并且无法改变。

**Comment by Zeus-Iqd** [comment]
现在解决了吗

**Comment by lemos1235** [comment]
同上

**Comment by super-noodle** [comment]
找到node_modules里面的vue-video-player/src/player.vue,初始化会有个videoOptions，修改一下里面的width可以设置默认宽度

**Comment by Leeoric** [comment]
这是video.js的问题，看到源码内对width和height做一次parseFloat。我的一个临时方案是
在组件mounted的时候找到放video的div，js设置宽度100%，希望有大神有更好的方案可以告知。

const domId = document.querySelector('.video-player-box').children[0].id
document.querySelector('#' + domId).style.width = '100%'

**Comment by surmon-china** [comment]
组件最新版 v5.0.0 已解决此问题。

**Comment by surmon-china** [comment]
已发布，记得删除 `node_modules` 重新安装。

**Comment by surmon-china** [comment]
已发布，记得删除 `node_modules` 重新安装。
