### ISSUE TITLE
Multiple Player Identification

### ISSUE THREAD

**Issue by schmokko** [surmon-china/vue-video-player#101]
Is it possible to add an ID or a name to the player component that it can be identified when using multiple player-components on one site?

**Comment by schmokko** [comment]
Maybe add something like this:

```
props: {
        playername:{
          type: String,
            required: false
        }
}

...

this.$el.children[0].setAttribute('name', playername)
```

**Comment by surmon-china** [comment]
You can get the element by `refs` attr.

**Comment by surmon-china** [comment]
1. spa 

<video-player :class="`player-${index}`" :ref="`player-${index}`">

2. ssr

https://github.com/surmon-china/vue-video-player/blob/master/ssr.js#L20
