### ISSUE TITLE
Initialise video dynamically

### ISSUE THREAD

**Issue by Spoowy** [surmon-china/vue-video-player#104]
What options are there to initialize a video dynamically?

Currently videos are initialised via loading the component and that is bad when you must set the video source et al dynamically.

Cheers,
Erwin

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-video-player/blob/master/src/player.vue#L157

In fact, when the configuration parameters of your incoming components change, the components will be released and re-initialized, which can meet your needs?

**Comment by zhoukk** [comment]
how in ssr ?

**Comment by Spoowy** [comment]
@surmon-china this is working very well! It's only when other plugins fail with non-existent data yet ( youtube embed) that causes me trouble.

I have fixed this simply by adding a state parameter to data: videoLoaded: false/true
and added a condition to the component:
`<video-player v-if="videoLoaded"...>`

This worked better than anticipated!

**Comment by surmon-china** [comment]
已发布，记得删除 `node_modules` 重新安装。

**Comment by mercs600** [comment]
@Spoowy I have familiar problem. When you set "videoLoaded" to true ? What do you mean when you have all the data for the video ?

**Comment by Spoowy** [comment]
@mercs600 By "data" I mean having the src-file-url and thumbnail-url which I get by making an ajax request.

**Comment by surmon-china** [comment]
Update to v5.0.1 please, you will can dynamic change options.

https://github.com/surmon-china/vue-video-player/blob/master/examples/01-video.vue#L66

**Comment by mercs600** [comment]
@Spoowy Ok, my problem is that I'm using youtube video as sources. 
@surmon-china I was trying change the source like on your example by: 
``` js
 this.playerOptions.sources[0].src = "youtube url"
```

but it doesn't work for me. Did you test it with videojs youtube plugin ?

**Comment by surmon-china** [comment]
@mercs600 In fact, as long as there is any change to your videoOptions, will the player release and reinitialize it, whether it's youtube or something else?

https://github.com/surmon-china/vue-video-player/blob/master/src/player.vue#L221

**Comment by mercs600** [comment]
@surmon-china after your last updated it works like a charm, thanks man !

**Comment by Bahroel0** [comment]
> @mercs600 In fact, as long as there is any change to your videoOptions, will the player release and reinitialize it, whether it's youtube or something else?
> 
> https://github.com/surmon-china/vue-video-player/blob/master/src/player.vue#L221

this is not working on Nuxt SSR mode.

**Comment by Bwijn** [comment]
> > @mercs600 In fact, as long as there is any change to your videoOptions, will the player release and reinitialize it, whether it's youtube or something else?
> > https://github.com/surmon-china/vue-video-player/blob/master/src/player.vue#L221
> 
> this is not working on Nuxt SSR mode. I use link from youtube as source.

add this directive  v-if  as :
```
 <div
      v-if="videoLoaded"
      class="video-player-box"

         @play="onPlayerPlay($event)"
         @pause="onPlayerPause($event)"
         @ready="playerReadied"
         @statechanged="playerStateChanged($event)"
         v-video-player:myVideoPlayer="playerOptions">
    </div>


```

I use it under the Nuxt and asyncData  is invalid because ‘’this‘’ cannot be obtained after rendering
