### ISSUE TITLE
手动切换视频问题

### ISSUE THREAD

**Issue by Orz-zzz** [surmon-china/vue-video-player#105]
直接修改playerOptions.sources.src属性
this.playerOptions.sources.src = 'http://vjs.zencdn.net/v/oceans.mp4'  //切换播放视频

但是player.vue  watch监听options配置变化时 
    //这里options.sources.length 条件为0是什么原因？ 导致initialize方法执行不了
    if (options && options.sources && options.sources.length) {
            this.initialize()
     }

**Comment by annyHu** [comment]
您好，请问下，是怎么监听地址变化的？
