### ISSUE TITLE
请问按照教程rtmp源播放不了

### ISSUE THREAD

**Issue by maplehsu** [surmon-china/vue-video-player#108]
![e1](https://user-images.githubusercontent.com/4917754/32544670-cb1ce9e2-c43e-11e7-9c65-244d64f8cd94.jpg)
![e2](https://user-images.githubusercontent.com/4917754/32544671-cb53640e-c43e-11e7-8b00-2a96286b8470.jpg)
以上是代码。hls的就没问题，rtmp报错：
video.cjs.js?0e26:441 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 
源：rtmp://live.hkstv.hk.lxdns.com/live/hks
但是我测试过源了可以使用的，而且在vue-video-player 3.0版本中这个源是可以直接打开的

**Comment by surmon-china** [comment]
如果你指的 “教程” 是文档，那么文档早就更新了，现在已经是 4.0.4 版本了。

https://github.com/surmon-china/vue-video-player/blob/master/examples/05-video.vue
