### ISSUE TITLE
video options start youtube

### ISSUE THREAD

**Issue by jcc2303** [surmon-china/vue-video-player#11]
Hi @surmon-china 

I was no able to start in a specific time of the video of youtube, am I doing something wrong?

thanks for the advice before.

```js
   {
        source: {
          type: 'video/youtube',
          src: 'https://www.youtube.com/watch?v=iD_MyDbP_ZE' 
        },
        start: 35,
        end: 65,
        techOrder: ['youtube'],
        autoplay: false,
        controls: false,
        ytControls: true
   }
   
```

**Comment by jcc2303** [comment]
Hi @surmon-china
maybe is the ready function? never is called?

**Comment by surmon-china** [comment]
1.update component to [2.3.2](https://github.com/surmon-china/vue-video-player/tree/v2.3.2)
2.add global config(you can find the example config code in [README.md](https://github.com/surmon-china/vue-video-player#install-vue-video-player))

```
VideoPlayer.config({
  youtube: true
})
```
