### ISSUE TITLE
RTMP模式下,有销毁player组件行为.就会报 this.el_.vjs_getProperty is not a function

### ISSUE THREAD

**Issue by Nick-Tsao** [surmon-china/vue-video-player#110]
请surmon关注一下.hls模式不会有这个问题.

**Comment by Nick-Tsao** [comment]
还有咱们首页 https://surmon-china.github.io/vue-video-player/ 和hls目前无法播放了.应该是video-hls那个依赖项的被严格模式打包了.

**Comment by Nick-Tsao** [comment]
![2017-11-14 5 31 50](https://user-images.githubusercontent.com/31433951/32772736-c5355e7e-c961-11e7-9677-fdd5fc2fdb43.png)
这是目前各版本号

**Comment by surmon-china** [comment]
好的 谢谢呀

**Comment by Nick-Tsao** [comment]
不客气,嘿嘿,我也是做hls找素材时候发现的.surmon很棒啊.让我少加班了,决定video的组件就用你的了.刚给的那个问题,为发现注释掉这段代码,就不报错了

**Comment by Nick-Tsao** [comment]
![ding](https://user-images.githubusercontent.com/31433951/32773991-e000b6c8-c965-11e7-8e80-d7746cfcf30e.jpeg)

**Comment by surmon-china** [comment]
对，这个问题已经有 PR 了，我抽时间合并下。

**Comment by Nick-Tsao** [comment]
好的,等你合并,我更新最新版本.哈哈. close issue

**Comment by surmon-china** [comment]
@Nick-Tsao 解决了，升级到 4.0.6.

**Comment by Nick-Tsao** [comment]
thank you
