### ISSUE TITLE
How to change the resolution of the video when using vue-video-player?

### ISSUE THREAD

**Issue by jiayouwyhit** [surmon-china/vue-video-player#111]
I am currently using vue-video-player. But I do not quite know how to change the video resolution.  Does vue-video-player support this? 

I know there is a package here: [https://github.com/kmoskwiak/videojs-resolution-switcher](https://github.com/kmoskwiak/videojs-resolution-switcher) . 
But it seems it is not compatible with vue-video-player.

**Comment by surmon-china** [comment]
Resolution switcher just support video.js v5.
