### ISSUE TITLE
how can I set the video width and height

### ISSUE THREAD

**Issue by zhangwei900808** [surmon-china/vue-video-player#114]
![image](https://user-images.githubusercontent.com/4385154/33071079-2ec42eae-cef5-11e7-9b3c-a7f45a8a5915.png)

**Comment by greenpdx** [comment]
In the playerOptions set the width and height

```
      playerOptions: {
        // videojs options
        muted: true,
        language: 'en',
        techOrder: ['html5', 'flvjs'],
        playbackRates: [0.7, 1.0, 1.5, 2.0],
        width: '800px',
        height: '800px',
        plugins: {

        },
        flash: {
          swf: './#/assets/video-js.swf'
        },
        poster: './#/assets/logo.png',
        sources: [
        ]
      }
    }
```

**Comment by nimoyao2** [comment]
亲测，代码如下，width: 800,heigh:600       
 playerOptions: {
          muted: true,                                // 关闭视频的声音通道（静音），属于逻辑属性
          language: 'en',
          autoplay: true,                                       //设置自动播放
          playbackRates: [0.7, 1.0, 1.5, 2.0],                  // 播放速率
          volume: 0.5,                                          // 初始的音量
          sources: [{
            type: "video/mp4",                                      // 播放格式
            src: "https://cdn.theguardian.tv/webM/2015/07/20/150716YesMen_synd_768k_vp8.webm"     // 播放源
          }],
          poster: "/static/images/author.jpg",       //当视频能够播放时，用于指定代表视频的图像的URL
          width: 500,             // 视频框的宽度
          height: 570,            // 视频框的高度
        }

**Comment by Leeoric** [comment]
You can dynamically check the video container's width, then set the width

e.g.
this.playerOptions.width = window.getComputedStyle(this.$refs.videoContainer).width

**Comment by surmon-china** [comment]
组件最新版已默认去除初始值，且可以自定义，请升级到 v5.0.0。

**Comment by surmon-china** [comment]
http://docs.videojs.com/tutorial-options.html#width

**Comment by surmon-china** [comment]
已发布，记得删除 `node_modules` 重新安装。

**Comment by 0LING0** [comment]
为什么我在playerOptions里面设置宽没有效果呢，width:'100px',审查元素后video区域宽高都为0
