### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by daiyang123456** [surmon-china/vue-video-player#117]
npm WARN vue-loader@8.7.0 requires a peer of vue-hot-reload-api@^1.2.0 but none was installed.
npm WARN vue-loader@8.7.0 requires a peer of vue-hot-reload-api@^1.2.0 but none was installed.

但是我已经安装了vue-hot-reload-api

**Comment by surmon-china** [comment]
这里是视频组件，不是 vue-loader 的 issues。
