### ISSUE TITLE
How to use any playback technology (YouTube, Wistia, Etc...) for Video.js using your package?

### ISSUE THREAD

**Issue by vishalmandora** [surmon-china/vue-video-player#118]
How to use https://github.com/videojs/videojs-youtube plugin with your package? please write me steps here.
Looking for exact steps from scratch to end.

**Comment by surmon-china** [comment]
Like this:

https://github.com/surmon-china/vue-video-player/blob/v3.0.0/examples/05-video.vue

**Comment by AKUmajinn** [comment]
Hi @surmon-china, would you consider add a wistia example in the future?
