### ISSUE TITLE
使用hls的时候报错 'EventTarget' of undefined

### ISSUE THREAD

**Issue by struts2012** [surmon-china/vue-video-player#127]
error: videojs-contrib-hls.js Uncaught TypeError: Cannot read property 'EventTarget' of undefined
vue-video-player: 4.0.6
videojs: 6.4.0
videojs-contrib-hls: 5.12.2

**Comment by surmon-china** [comment]
最新版本 v5.0.0 解决此问题。需要删除 node_modules，重新安装。

**Comment by surmon-china** [comment]
已发布，记得删除 `node_modules` 重新安装。

**Comment by sunxiang0918** [comment]
还是不行... 还是在报: Uncaught TypeError: Cannot read property 'EventTarget' of undefined

**Comment by shangTou** [comment]
@sunxiang0918 试试这样引入 import 'videojs-contrib-hls';

**Comment by xumiaojun** [comment]
TypeError: Cannot read property 'EventTarget' of undefined，只要引入import "videojs-contrib-hls/dist/videojs-contrib-hls" 就报错！

**Comment by niwho** [comment]
解决，如@shangTou所述

**Comment by Hlianfa** [comment]
这个问题又出现了

**Comment by wangweigit3077** [comment]
不行啊   还是有问题

**Comment by caoruiy** [comment]
目前尝试了 `import "videojs-contrib-hls/dist/videojs-contrib-hls"` `import "videojs-contrib-hls` ，`node_modules`删除重装，均报错。
```
"videojs-contrib-hls": "5.14.1",
"vue-video-player": "^5.0.2",
```


回退 `vue-video-player` 到版本 `4.0.6`。可以使用，不会报错。

```js
import 'videojs-contrib-hls/dist/videojs-contrib-hls'
```

**Comment by xlfdyzcs** [comment]
> 目前尝试了 `import "videojs-contrib-hls/dist/videojs-contrib-hls"` `import "videojs-contrib-hls` ，`node_modules`删除重装，均报错。
> 
> ```
> "videojs-contrib-hls": "5.14.1",
> "vue-video-player": "^5.0.2",
> ```
> 
> 回退 `vue-video-player` 到版本 `4.0.6`。可以使用，不会报错。
> 
> ```js
> import 'videojs-contrib-hls/dist/videojs-contrib-hls'
> ```

有用
