### ISSUE TITLE
hls播放10秒卡死

### ISSUE THREAD

**Issue by acodercat** [surmon-china/vue-video-player#128]
用edge浏览器就正常，其他任何浏览器10秒卡死

**Comment by surmon-china** [comment]
极大可能，是你 HLS 源的问题，其次，有可能是 HLS 默认配置与源有不兼容问题，你可以参考，hls 插件官方文档对各种参数进行调节，组件只是一个粘合剂，解决不了那些来自插件的问题。

**Comment by lucyluozz** [comment]
> 用edge浏览器就正常，其他任何浏览器10秒卡死

这个问题你最后你解决了吗？ 我遇到了同样的问题
