### ISSUE TITLE
移动端，微信公众网页。竖屏点击播放后，旋转屏幕到横屏，再旋转回竖屏，关闭视频。回到的页面头部会被遮挡一半。

### ISSUE THREAD

**Issue by lsqswl** [surmon-china/vue-video-player#133]
如题

**Comment by surmon-china** [comment]
比较建议，在 IOS safari 下连接 USB 开启PC端联调，重要是审查 DOM，这和 Dom 密切相关。这个问题涉及到你自己的业务，有大量自身的业务内容，在这里基本不会有人帮得到你的，因为没有人能复现你的场景。

**Comment by xzzfxz** [comment]
我也遇到了，请问有解决办法吗。
我的是整体往右上偏移，我直接改html根元素的margin-left值，发现还没到屏幕边缘，dom元素就被隐藏了，在左边有一列空白。
