### ISSUE TITLE
能支持字幕吗

### ISSUE THREAD

**Issue by huanghanzhilian** [surmon-china/vue-video-player#134]
能支持字幕吗

**Comment by surmon-china** [comment]
https://www.google.com.hk/search?newwindow=1&ei=xOZUWve0OYiv0ASRvrbwDg&q=videojs+subtitle&oq=videojs+subtitle&gs_l=psy-ab.3..0i71k1l4.3120.3120.0.3327.1.1.0.0.0.0.0.0..0.0....0...1c.1.64.psy-ab..1.0.0....0.gZ2TJhIdp4Y

像这样去寻找答案
