### ISSUE TITLE
nuxt下,视频下方的按钮图标不显示

### ISSUE THREAD

**Issue by Owen-Dee** [surmon-china/vue-video-player#135]
按照示例,在nuxt下，页面视频可以播放,视频下方的暂停和其他按钮图标都不显示。

**Comment by surmon-china** [comment]
`controls: true`

**Comment by Owen-Dee** [comment]
不好意思,可能说的不是太清楚,视频下方的控制条可以显示，但 暂停，声音，全屏 的按钮图标不显示，这三个按钮在页面上的显示就是三个白色方框，是还需要设置其它属性么？

**Comment by surmon-china** [comment]
@Owen-Dee 截个图看一下

**Comment by Owen-Dee** [comment]
![test](https://user-images.githubusercontent.com/27292570/34904962-cc3b26a6-f88a-11e7-8242-e501c24f8d29.png)

**Comment by Owen-Dee** [comment]
![test2](https://user-images.githubusercontent.com/27292570/34905021-9e4dfe20-f88b-11e7-8d4c-a0bbe1a9013a.png) 开始按钮是有的，下方的几个按钮，是不是在nuxt下一些样式没有加载进去？

**Comment by surmon-china** [comment]
你引入的 CSS 有哪些

**Comment by Owen-Dee** [comment]
![1](https://user-images.githubusercontent.com/27292570/34905218-278537f0-f88f-11e7-8ba4-f0a65c3ede36.png)
我把这两个都引进来了

**Comment by Owen-Dee** [comment]
![2](https://user-images.githubusercontent.com/27292570/34905293-9819ccaa-f890-11e7-8125-b1fa48c73810.png)
样式被引进来了，是不是对应的字体样式没被引进来？

**Comment by surmon-china** [comment]
要不你留下项目地址，我在本地测试，一切正常，无法复现

**Comment by surmon-china** [comment]
![image](https://user-images.githubusercontent.com/14019524/34905435-5b76acde-f893-11e7-83de-3ae10ab71dcf.png)

**Comment by Owen-Dee** [comment]
谢谢你的回复，我又重新打了一套环境，测试了一下，又有了

**Comment by surmon-china** [comment]
好的
