### ISSUE TITLE
使用cdn，options使用method设置，会出现video只有声音

### ISSUE THREAD

**Issue by OrinQin** [surmon-china/vue-video-player#136]
前辈你好，我想请问一下下列情况是我使用方式上的问题么，新手问题可能比较小白，请多担待
（Hello, my predecessor, I would like to ask if the following situations are the problems I use. The novice problem may be foolish. Please be more patient.）
我是在v-for中使用的video-player组件，options这样设置的：
（I am the video-player component used in v-for, and the options are set as follows:）
`:options="getOptions(index)"`
`getOptions(index){

    var videoL = this.videoList;

    var playerOps = {

        width: '300',

        autoplay: false,

        preload: "none",

        muted: false,

        language: 'en',

        playbackRates: [0.7, 1.0, 1.5, 2.0],

        poster: videoL[index].posterURL

    }

    if (this.url2mp4List.indexOf("" + index) != -1) {

        playerOps.sources = [{

            type: "video/mp4",

            // mp4

            src: videoL[index].videoURL,

            // webm

            // src: "https://cdn.theguardian.tv/webM/2015/07/20/150716YesMen_synd_768k_vp8.webm"

        }];

    }

    console.log("---------------" + JSON.stringify(playerOps));

    return playerOps;
}`
这样使用时，getOptions的返回值与data中的options一致，会出现：
（When used in this way, the return value of getOptions is consistent with the options in data, which will appear:）
1.播放控制按钮都没有
（There is no play control button.）
2.使用:key刷新video-player所在的节点会出现声音，但是画面和播放控制的button也都还是没有
（Use: key refreshes the video - player's node will be heard, but the image and the playback button are still not there）

**Comment by OrinQin** [comment]
我一开始我是搜索到了这篇中前辈您的回复，就尝试着用函数去返回options
https://github.com/surmon-china/vue-video-player/issues/80
但是同样的数据显示的效果缺不一样不知道是什么原因

**Comment by OrinQin** [comment]
前辈您好，我已经解决了，video-player不重新初始化是videojs的硬伤，我在直接使用videojs时发现了，所以只有声音是我的问题不是这个vue-video-player的，最后因为我的实际需求只是更换src而不是全盘更改options，而后来我领悟到vue-video-player除了适配vue之外，其本质还是videojs，所以我写了这么几个方法
`                getPlayer: function(index) {
                    return this.$refs.videoPlayer[index].player
                },
                setSrc:function(index){
                    var clickPlayer = this.getPlayer(index);
                    clickPlayer.src(this.videoList[index].videoURL);
                    clickPlayer.play();
                },`
感谢插件提供，受益很大

**Comment by surmon-china** [comment]
还有一种：可以在列表每个元素维护一个类似 `canPlay` 的字段；`setSrc`方法，每次更新完 src 数据后，对这个对应的元素，把他的 `canPlay` 设置为 false， nextTick 时再设置为 true。略麻烦，哈哈哈。其实组件内部已经做了这方面的处理了，但实际情况复杂，不能完全工作。

https://github.com/surmon-china/vue-video-player/blob/master/src/player.vue#L216

**Comment by surmon-china** [comment]
这个问题，在今天有重新解决，可以参考 #104 

https://github.com/surmon-china/vue-video-player/blob/master/examples/01-video.vue#L66
