### ISSUE TITLE
切换路由时会一直报this.el_.vjs_getProperty is not a function的错，返回播放的界面就显示黑屏了，我看到这个问题之前被解决过，但是现在好像又出现了，急用，请作者大大看一下

### ISSUE THREAD

**Issue by yjl000** [surmon-china/vue-video-player#137]
<template>
  <div class="classLive">
    <div class="videoWindow">
      <video-player class="vjs-custom-skin" :options="playerOptions">
      </video-player>
    </div>
    <div class="classList"></div>
  </div>
</template>

<script type="text/ecmascript-6">
import 'video.js/dist/video-js.css'
import {videoPlayer} from 'vue-video-player'
import 'videojs-flash'
export default {
  data () {
    return {
      playerOptions: {
        // videojs options
        sources: [{
          type: 'rtmp/mp4',
          src: 'rtmp://192.168.11.147:1935/live/e0f3a88a7535fd3_1_1',
          withCredentials: false
        }],
        techOrder: ['flash'],
        autoplay: true,
        controls: true
      }
    }
  },
  components: {
    videoPlayer
  }
}
</script>

<style lang="stylus" rel="stylesheet/stylus">
  @import "~common/stylus/variable"

  .classLive
    width $main-width
    margin 0 auto
</style>

**Comment by chiaweilee** [comment]
这个应该不是插件的问题，可能是使用方法的问题。

我猜测：vue切换路由时原对象被destory了，所以你切换回来时当然是undefined了。可以尝试使用Keep-alive。

仅供参考。

**Comment by yjl000** [comment]
路由时使用了keep-alive了的

**Comment by yjl000** [comment]
好吧，是路由不能使用keep-alive,我注释掉keep-alive就不报错了，我用的最新的谷歌，有办法解决这个问题嘛，因为蛮多情况要使用keep-alive的

**Comment by chiaweilee** [comment]
按照你的试了下，我这正常。你试试把去掉`techOrder: ['flash']`呢？坐等大神

**Comment by surmon-china** [comment]
rtmp 依赖 flash，必须使用 flash；keep-alive 可以设置作用组件、排除组件，查查官网文档就知道了。

**Comment by yjl000** [comment]
不是很明白，flash必须要设置的，就是用keep-alive切换路由时就会报错，用了360浏览器和火狐试了一下，也是一样的问题

**Comment by surmon-china** [comment]
@yjl000 https://cn.vuejs.org/v2/api/#keep-alive

**Comment by surmon-china** [comment]
`<keep-alive exclude="video-player">`
