### ISSUE TITLE
麻烦作者大大再看一下，引入vue-video-player时head加入的这个style去哪里改默认值，我的窗口没有那么大，但是会自动跳到1280X720,非常感谢

### ISSUE THREAD

**Issue by yjl000** [surmon-china/vue-video-player#138]
<style class="vjs-styles-dimensions">
      .vjs_video_1849-dimensions {
        width: 1280px;
        height: 720px;
      }

      .vjs_video_1849-dimensions.vjs-fluid {
        padding-top: 56.25%;
      }
    </style>

**Comment by surmon-china** [comment]
不是所有的问题都和组件有关啊，想办法自己解决。

**Comment by passioncsu** [comment]
我也是这个问题啊。。。。既然和组件没关系难道我哪里写错了嘛。反正就是视频加载后太大了。我暂时通过操作dom设置大小，但是我这个解决办法也太low 了，有没有谁有更好的办法，难道不是默认不超过父div尺寸嘛。最后谢谢作者的辛勤劳动。

**Comment by surmon-china** [comment]
这里面包含了两部分css，都是通过开发者手动引入的，一个是 videojs 本身的（`video-js.css`），一个是定制的主题（`custom-theme.css`），两个 css 文件都没有对宽高尺寸做过约束；

你说是在 `<head>` 加入，那么可能与 webpack 开发模式有关，更可能的是与 videojs 的工作机制有关，如果是 videojs 工作机制产生的，那么可能需要读一下文档了...

**Comment by passioncsu** [comment]
我特地回来说一声,我之前可能是瞎了, 人家管网demo的设置就有啊  那么大个字我都看不到
playerOptions: {
        height: '212'
}
在这里设置就好了啊....唉 活该我在这个上卡了这么多天
