### ISSUE TITLE
Unsupported fullscreenchange event？

### ISSUE THREAD

**Issue by irenexixi** [surmon-china/vue-video-player#142]
Unsupported fullscreenchange event？

**Comment by surmon-china** [comment]
You can convert some videojs events to component events like below.

```javascript
Vue.use(VueVideoPlayer, /* {
  options: global default options,
  events: [ ... global videojs events ]
} */)
```

```html
<video-player :events="[ ...someVideojsEvent ]"/>
```

**Comment by irenexixi** [comment]
I try like this, but it does't trigger the event. Whether it is the events param incorrect.
![image](https://user-images.githubusercontent.com/7159225/35479410-c0b97532-0431-11e8-8bbe-017813c2d6f7.png)
![image](https://user-images.githubusercontent.com/7159225/35479412-d17116dc-0431-11e8-932b-285e8ed4891e.png)
![image](https://user-images.githubusercontent.com/7159225/35479414-d982cdac-0431-11e8-92e0-eb2299dc81dd.png)
![image](https://user-images.githubusercontent.com/7159225/35479415-e66fa79c-0431-11e8-9d9c-1b67d7fefd92.png)

**Comment by irenexixi** [comment]
@surmon-china Could you help me find the error ？ It still can't work.

**Comment by surmon-china** [comment]
the v5.0.2 fix it.

**Comment by irenexixi** [comment]
@surmon-china Fixed！Good！
