### ISSUE TITLE
在安卓的微信里视频播放的时候自动全屏的问题

### ISSUE THREAD

**Issue by joneqian** [surmon-china/vue-video-player#144]
环境:
华为mate8
微信6.6.2
问题：
视频点击播放后，自动全屏（已经将playsinline设置成true）

代码：
playerOptions: {
  playsinline: true,
  muted: false,
  language: 'zh',
  sources: [{
    type: 'video/mp4',
    src: item.url
  }],
  poster: item.cover
 }

**Comment by surmon-china** [comment]
这和组件没有关系，是微信本身对视频的处理，无法避免。

**Comment by shangTou** [comment]
@joneqian 最近几天赶项目的时候刚好碰到这个问题
我的解决方法是： 把源码文件中的x5-video-player-type的属性去掉，实测多台安卓机子在微信中没有问题，你可以试试~

**Comment by junshaochen** [comment]
@shangTou 确实可以，谢啦

**Comment by pocketChao** [comment]
> @joneqian最近几天赶项目的时候刚好碰到这个问题
> 我的解决方法是：把源码文件中的x5-video-player-type的属性去掉，实测多台安卓机子在微信中没有问题，你可以试试〜

哥们儿  这个是去掉// ios fullscreen
        if (this.playsinline) {
          this.$refs.video.setAttribute('playsinline', this.playsinline)
          this.$refs.video.setAttribute('webkit-playsinline', this.playsinline)
          this.$refs.video.setAttribute('x5-playsinline', this.playsinline)
          **this.$refs.video.setAttribute('x5-video-player-type', 'h5')**
          this.$refs.video.setAttribute('x5-video-player-fullscreen', false)
        }中的type么

**Comment by shangTou** [comment]
> > @joneqian最近几天赶项目的时候刚好碰到这个问题
> > 我的解决方法是：把源码文件中的x5-video-player-type的属性去掉，实测多台安卓机子在微信中没有问题，你可以试试〜
> 
> 哥们儿 这个是去掉// ios fullscreen
> if (this.playsinline) {
> this.$refs.video.setAttribute('playsinline', this.playsinline)
> this.$refs.video.setAttribute('webkit-playsinline', this.playsinline)
> this.$refs.video.setAttribute('x5-playsinline', this.playsinline)
> **this.$refs.video.setAttribute('x5-video-player-type', 'h5')**
> this.$refs.video.setAttribute('x5-video-player-fullscreen', false)
> }中的type么

这么长时间我也忘记了 源码在前公司 不好意思 你可以试试注释一下看看~

**Comment by pocketChao** [comment]
好的 谢谢   还是不好用

**Comment by hzjump** [comment]
> 环境:
> 华为mate8
> 微信6.6.2
> 问题：
> 视频点击播放后，自动全屏（已经将playsinline设置成true）
> 
> 代码：
> playerOptions: {
> playsinline: true,
> muted: false,
> language: 'zh',
> sources: [{
> type: 'video/mp4',
> src: item.url
> }],
> poster: item.cover
> }

这个问题解决了吗？iOS在微信中的表现还可以，但是安卓就不行了，一点击就全屏

**Comment by forever-chun** [comment]
> 好的谢谢还是不好用

兄弟，现在问题解决了嘛？

**Comment by forever-chun** [comment]
> > 环境：
> > 华为mate8 
> > 微信6.6.2 
> > 问题：
> > 视频点击播放后，自动全屏（已经将playsinline设置成真）
> > 代码：
> > playerOptions：{ 
> > playsinline：true，
> > muted：false，
> > language：'zh'，
> > sources：[{ 
> > type：'video / mp4'，
> > src：item.url 
> > }]，
> > poster：item.cover 
> > }
> 
> 这个问题解决了吗？iOS的在微信中的表现还可以，但是安卓就不行了，一点击就全屏

兄弟，这个问题你是怎么解决的？

**Comment by pocketChao** [comment]
> > > 环境：
> > > 华为mate8 
> > > 微信6.6.2 
> > > 问题：
> > > 视频点击播放后，自动全屏（已经将playinline设置成真）
> > > 代码：
> > > playerOptions：{ 
> > > playsinline：true，
> > > muted：false，
> > > language：'zh'，
> > > sources：[{ 
> > > type： 'video / mp4'，
> > > src：item.url 
> > > }]，
> > > poster：item.cover 
> > > }
> > 
> > 
> > 这个问题解决了吗？iOS版的在微信中的表现还可以，但是安卓就不行了，一点击就全屏
> 
> 兄弟，这个问题你是怎么解决的？

在vue-video-player.js 源码中删除 x5-video-player-type="h5"，暂时解决了这个问题

**Comment by forever-chun** [comment]
> > > > 环境：
> > > > 华为mate8 
> > > > 微信6.6.2 
> > > > 问题：
> > > > 视频点击播放后，自动全屏（已经将playinline设置成真）
> > > > 代码：
> > > > playerOptions：{ 
> > > > playsinline：true，
> > > > muted：false，
> > > > language：'zh'，
> > > > sources：[{ 
> > > > type： 'video / mp4'，
> > > > src：item.url 
> > > > }]，
> > > > poster：item.cover 
> > > > }
> > > 
> > > 
> > > 这个问题解决了吗？的iOS版的在微信中的表现还可以，但是安卓就不行了，一点击就全屏
> > 
> > 
> > 兄弟，这个问题你是怎么解决的？
> 
> 在vue-video-player.js源码中删除x5-video-player-type =“h5”，暂时解决了这个问题

我的小白，不太懂，vue-video-player.js源码中我没找到这个代码x5-video-player-type =“h5”

**Comment by pocketChao** [comment]
> > > > > 环境：
> > > > > 华为mate8 
> > > > > 微信6.6.2 
> > > > > 问题：
> > > > > 视频点击播放后，自动全屏（已经将playinline设置成真）
> > > > > 代码：
> > > > > playerOptions：{ 
> > > > > playsinline：true，
> > > > > muted：false，
> > > > > language：'zh'，
> > > > > sources：[{ 
> > > > > type： 'video / mp4'，
> > > > > src：item.url 
> > > > > }]，
> > > > > poster：item.cover 
> > > > > }
> > > > 
> > > > 
> > > > 这个问题解决了吗？的的iOS版的在微信中的表现还可以，但是安卓就不行了，一点击就全屏
> > > 
> > > 
> > > 兄弟，这个问题你是怎么解决的？
> > 
> > 
> > 在vue-video-player.js源码中删除x5-video-player-type =“h5”，暂时解决了这个问题
> 
> 我的小白，不太懂，vue-video-player.js源码中我没找到这个代码x5-video-player-type =“h5”

搜索下把

**Comment by callmesoul** [comment]
初步试了下
|          | playsinline=true | playsinline=false |
| -------- | ---------------- | ----------------- |
| 原生安卓 | ✔                | ❌                 |
| 原生ios  | ✔                | ❌                 |
| 微信安卓 | ❌                | ✔                 |
| 微信ios  | ✔                | ❌                 |

也就是出了微信安卓为false 其他都为true
```
var u = navigator.userAgent;
      var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1; //android终端
      var ua = window.navigator.userAgent.toLowerCase();
      if (ua.match(/MicroMessenger/i)[0] == 'micromessenger') {
        // 微信
        if(isAndroid){
          this.playsinline=false
        }
      }
```
Iphone 6 和 锤子手机 上测试
