### ISSUE TITLE
切换路由时一直报错this.el_.vjs_getProperty is not a function

### ISSUE THREAD

**Issue by wangjun0868** [surmon-china/vue-video-player#159]
浏览了一遍关闭的issues看到一些解决方案，keep-alive以及其他的注释掉源码的一些代码，但是切换路由的时候还是出现同样的问题，版本情况
![image](https://user-images.githubusercontent.com/34526789/38241540-13150984-3765-11e8-8463-6dc38bffec00.png)

当前的版本怎么能够有效的解决呢，请大神支招。

**Comment by surmon-china** [comment]
实在对不住，我也不太知道

**Comment by xuange306** [comment]
请问,问题解决了吗?同样出现了这个问题

**Comment by viccowang** [comment]
建议修改文件 player.vue中的钩子函数. 添加 activated和 deactivated.  可以在deactivated中调用源方法 this.dispose() 来销毁player. 然后再 activated 调用 this.initialize() 重新初始化player.

我是这么修正的.

**Comment by imakan** [comment]
增加选项 preload: 'auto'

**Comment by liuchangliuliu** [comment]
import VideoPlayer from 'vue-video-player'
import 'video.js/dist/video-js.css'
VideoPlayer.config({
  youtube: true, // default false
  switcher: false, // default true
  hls: true // default true
});

// use
Vue.use(VideoPlayer)

但是一直报错  __WEBPACK_IMPORTED_MODULE_22_vue_video_player___default.a.config is not a function

**Comment by MuyNooB** [comment]
我说下问题出现的原因哈，只要 video 元素从 dom 树上面移除就会报这个错，可在控制台 Element 面板找到这个元素，然后右键菜单 Delete element，然后就会出现错误。
在 vue 中就找对应的不要让 video element 移除的方法。
videojs 没看源码，但是实话：好chun
