### ISSUE TITLE
如何隐藏ios中默认的控制栏

### ISSUE THREAD

**Issue by dandelion-Chen** [surmon-china/vue-video-player#160]
你好，我引用vue-video-player@5.02版本，在ios中默认控制栏存在，只想显示插件所带的控制栏，请问有什么办法可以去掉吗？
![](https://github.com/dandelion-Chen/dandelionChen.io/raw/master/issues/vue-player.png)

**Comment by 857128237** [comment]
安卓能隐藏默认控制栏吗
