### ISSUE TITLE
Live(04) example does not work

### ISSUE THREAD

**Issue by kslr** [surmon-china/vue-video-player#181]
#### Vue.js version and component version
2.5.16
#### Steps to reproduce
Run  [https://github.com/surmon-china/vue-video-player/blob/master/examples/04-video.vue](https://github.com/surmon-china/vue-video-player/blob/master/examples/04-video.vue) 

=> No compatible source was found for this media.
Is it because of dependency changes?

**Comment by luoyang125024608** [comment]
I have the same problem
dependencies is lastest but it dose not work

**Comment by xxhy1989** [comment]
is resolved ?

**Comment by kslr** [comment]
@xxhy1989 No, have given up

**Comment by alterhu2020** [comment]
how to make it works as the website: https://github.com/surmon-china/vue-video-player/blob/master/examples/04-video.vue, Hi Team. @surmon-china

**Comment by kslr** [comment]
For now, you don't need to use vue adaptation.
