### ISSUE TITLE
在使用 rtmp 时  已引入 “videojs-flash” 还是会报错

### ISSUE THREAD

**Issue by wangyano0** [surmon-china/vue-video-player#183]
![image](https://user-images.githubusercontent.com/11673604/40960063-2ccad1ae-68d1-11e8-9eb8-cb6c9d285237.png)

**Comment by wangyano0** [comment]
![image](https://user-images.githubusercontent.com/11673604/40963554-7e914a86-68db-11e8-935d-3c1f5af52a26.png)
 vue-video-palyer的版本已经是5.0以上了，还是不能解决

**Comment by ghostJun** [comment]
同样的问题，是否有解决方案

**Comment by shen-lan** [comment]
解决了吗

**Comment by shen-lan** [comment]
> 同样的问题，是否有解决方案
怎么解决的？
