### ISSUE TITLE
有纯音频播放吗？

### ISSUE THREAD

**Issue by lsl233** [surmon-china/vue-video-player#20]
在移动端播放器会自动全屏 ， 有纯音频播放 或 其他不，播放的时候不自动全屏的解决方案吗？

**Comment by surmon-china** [comment]
视频播放的话有解决方案，是使用canvas实现的；
纯音频播放器还没有，音频播放器的需求过于定制化，目前有很多音频库可以做到，建议可以尝试自行搭建一个音频类的组件。
