### ISSUE TITLE
请问为什么最新版会报错呢？ 

### ISSUE THREAD

**Issue by cn-Meepo** [surmon-china/vue-video-player#211]
安装好之后启动就报这个错误 Can't resolve 'videojs' in 'D:\project\vue\node_modules\vue-video-player\dist'

**Comment by mimimile** [comment]
我也出现了这个问题

**Comment by mimimile** [comment]
@cn-Meepo 
```
alias: {
            videojs: 'video.js'
}
```
加这个就可以了

**Comment by wct-cpp** [comment]
加哪里呢

**Comment by AkenClub** [comment]
> 加哪里呢

![image](https://user-images.githubusercontent.com/52781316/172122401-7f9cd56d-e8a9-4167-9f06-5b178335aa6c.png)
