### ISSUE TITLE
How do you set autoreplay or repeat video automatically

### ISSUE THREAD

**Issue by valjar** [surmon-china/vue-video-player#215]
Hi! 

Just one question. How do you set video to repeat on autoplay so my video would play continuously?

Thank you for your answer!

BR,
Davor

**Comment by mengLLLL** [comment]
same question

**Comment by dreglad** [comment]
You can pass any valid Video.js option to the component's `options` prop

Take a look at the [`loop` option](https://docs.videojs.com/tutorial-options.html#loop)

#### Example
```html
<template>
  <video-player :options="playerOptions" />
</template>
```
```javascript
export default {
   ...
   data () {
    return {
      playerOptions: {
        loop: true,
        ...
      }
    }
  }
}
```

**Comment by valjar** [comment]
Ah :)
Thank you!
