### ISSUE TITLE
如何动态添加视频源src?

### ISSUE THREAD

**Issue by indextg** [surmon-china/vue-video-player#229]
现在业务要求是有一个列表每个上面都有一个开始直播的按钮，点哪个进行直播哪个的视频，我给每个
this.$refs.videoPlayer.player.src = "XXXXXX",并不起作用，请问这个该怎么做？

**Comment by Hlianfa** [comment]
在options里设置sources，this.playerOptions.sources=[{type:"",src:""}]，多去看example吧

**Comment by 383366204** [comment]
@Hlianfa 请问在如何切换sources里正在播放的视频？我的是直播视频，sources里有多个元素，想问一下有没有方法可以切换到下一个视频或者上一个视频？我找了很久都找不到

**Comment by mcmf** [comment]
this.playerOptions.sources[0].src = xxx

**Comment by AKclown** [comment]
不可以呐
