### ISSUE TITLE
在微信公众号播放rtmp视频

### ISSUE THREAD

**Issue by zhangdoudou** [surmon-china/vue-video-player#251]
使用微信公众号播放rtmp，播放不了，是这个插件的问题吗？大家有什么好的插件推荐吗？

**Comment by zhangdoudou** [comment]
实在是抱歉，查阅相关资料得知，移动端播放只能支持hls格式的，打扰了

**Comment by cdscawd** [comment]
> 实在是抱歉，查阅相关资料得知，移动端播放只能支持hls格式的，打扰了

请问下 你的问题解决了吗？我这有个别人的rtmp协议视频流，需要在移动端播放，

**Comment by gdoudeng** [comment]
> 实在是抱歉，查阅相关资料得知，移动端播放只能支持hls格式的，打扰了

我还以为是我的问题。。。原来压根就不支持
