### ISSUE TITLE
Adding plugins to the video player component

### ISSUE THREAD

**Issue by braseidon** [surmon-china/vue-video-player#254]
Anyone figure out a way to add plugins to the vue-video-player component without having to hack the individual plugin sources?

**Comment by braseidon** [comment]
I figured out the issue with videojs plugins not working when included in my Vue component. The video.js dependency for a lot of plugins is a different version than the one that vue-video-player uses. This makes the plugins hook into another instance of video.js.

I forced the plugins to all use the same version of their video.js dependencies and they worked perfectly.

**Comment by k0d3rR** [comment]
@braseidon Would it be possible for you to share how did you solve this issue? I am stuck trying to understand how you managed to make the plugins use the same version of video.js

In my case, they are all using the same version.

Thanks
