### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by greenpdx** [surmon-china/vue-video-player#257]
### 中文用户注意：

1. 尽量用英文描述你的 issue
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，必须仔细阅读 REMADE.md + 在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决
5. **如果无法做到提一个合格、优秀的问题，则问题会被 close + block**

#### Vue.js version and component version
3.4.1
#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/
This has to do with CORS so setting up would require an internet server, but I do not have the ability.
#### Steps to reproduce
Load a video with

```
options: {
    crossOrigin: 'Anonymous
}
``` '

#### What is Expected?      
before I click play, the video tag has crossOrigin is set to null.

when I play is plays fine but when I transfer it to a canvas and then try to 
  let data = ctx.getImageData(0,0,w,h)

I should get data

#### What is actually happening?

I get  DOMException: "The operation is insecure."

This means that crossOrigin is not set. on the video element
I then checked the value and it is not set.

**Comment by greenpdx** [comment]
It is passed as a props, not as option.

**Comment by 690797590** [comment]
Thanks,i use 'crossOrigin="Anonymous"' as prop,it works!
