### ISSUE TITLE
iOS设备(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)

### ISSUE THREAD

**Issue by ritayzy** [surmon-china/vue-video-player#3]
你好，我使用这个插件，做了一个demo，在pc浏览器（chrome上面DevTool模式）可以正常播放m3u8文件，在移动设备上面无法播放，
下面是调用代码

```

<template>
  <video-player :options="videoOptions"></video-player>
</template>

<script>
  import Vue from 'vue';
  import VideoPlayer from 'vue-video-player';

  Vue.use(VideoPlayer);

  export default {
    data() {
      return {
        videoOptions: {
          source: {
            type: 'application/x-mpegURL', 
            src: 'http://192.168.1.56/live/livestream.m3u8',
            withCredentials: false
          },
          live: true,
          autoplay: true
        }
      };
    }
  };
</script>

<style>
  * {
    margin: 0;
    padding: 0;
  }
</style>

```

在pc上面的播放效果，如图

![image](https://cloud.githubusercontent.com/assets/18484770/19221284/f27a11ca-8e72-11e6-97ae-7d86831d8659.png)

 在iOS设备上面会出现下面的错误

![wechatimg3](https://cloud.githubusercontent.com/assets/18484770/19221294/1a4c3e76-8e73-11e6-9f3f-c92e1b32610a.jpeg)

用safari调试这个错误，控制台报下面的错误

![image](https://cloud.githubusercontent.com/assets/18484770/19221302/45a14b48-8e73-11e6-8ed2-f9b2bdafdd26.png)

希望可以帮忙看下，谢谢了！

**Comment by surmon-china** [comment]
明天我会测试一下，严格来说当前可用的IOS/Mac OS系统都是原生支持Hls流媒体的，谢谢你的反馈

**Comment by ritayzy** [comment]
你好，我这边把内网ip换成外网ip就可以在手机上面用了，已经可以了 @surmon-china ，谢谢你。

**Comment by surmon-china** [comment]
OK，看来是代理没配好导致的啊。。。
