### ISSUE TITLE
官网rtmp列子播放不了

### ISSUE THREAD

**Issue by zqtlin** [surmon-china/vue-video-player#305]
官网上的rtmp例子无法播放

**Comment by StephenOo** [comment]
> 官网上的rtmp例子无法播放

这个怎么解决的？遇到了同样的问题rtmp无法播放

**Comment by zqtlin** [comment]
浏览器要设置允许flash运行

**Comment by nongzhenli** [comment]
> 浏览器要设置允许flash运行

你好，我已经社会 允许云顶 false了，还是不行，请问依照您的经验，有什么建议么？
![image](https://user-images.githubusercontent.com/19389294/64951061-87c19d00-d8af-11e9-88d4-c0f169c10433.png)

**Comment by kongta** [comment]
> > 浏览器要设置允许flash运行
> 
> 你好，我已经社会 允许云顶 false了，还是不行，请问依照您的经验，有什么建议么？
> ![image](https://user-images.githubusercontent.com/19389294/64951061-87c19d00-d8af-11e9-88d4-c0f169c10433.png)

> 你好 请问你最后怎么解决的
