### ISSUE TITLE
electron下，播放等字体图标不显示

### ISSUE THREAD

**Issue by Eline2017** [surmon-china/vue-video-player#315]
### 中文用户注意：

1.已经引入了样式文件；
![image](https://user-images.githubusercontent.com/23447167/62857313-dc5e7f00-bd29-11e9-8ae7-ea298cf7f968.png)
2.字体图标无法正常显示；
![image](https://user-images.githubusercontent.com/23447167/62857338-ee402200-bd29-11e9-80a4-fec979b5e46f.png)

**Comment by Eline2017** [comment]
已解决

**Comment by pengandpeng** [comment]
> 已解决

请问怎么解决的呢，遇到同样的问题了。

**Comment by Eline2017** [comment]
我这边是重新写了一下该插件所用的字体图标，大致如图所示：





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pengandpeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 下午5:48
收件人:&nbsp;"surmon-china/vue-video-player"<vue-video-player@noreply.github.com&gt;;
抄送:&nbsp;"Eline_弥漫"<1165727688@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [surmon-china/vue-video-player] electron下，播放等字体图标不显示 (#315)



 
已解决
  
请问怎么解决的呢，遇到同样的问题了。

**Comment by sweetylulu** [comment]
> 已解决

怎么解决的
