### ISSUE TITLE
关于切换 source  后 playbackRates 显示问题

### ISSUE THREAD

**Issue by puzzle9** [surmon-china/vue-video-player#33]
切换 source  前将 playbackRates  设为 100x 实际为 100x
切换 source 后 playbackRates  显示为 100x 实际为 1x

**Comment by surmon-china** [comment]
随后修复，感谢反馈

**Comment by ghostsatan** [comment]
> 随后修复，感谢反馈

动态设置了 播放的src  playbackRates 就不显示了
