### ISSUE TITLE
videojs-contrib-hls warning

### ISSUE THREAD

**Issue by jenky** [surmon-china/vue-video-player#34]
`./~/videojs-contrib-hls/dist/videojs-contrib-hls.js
Critical dependencies:
This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/videojs-contrib-hls/dist/videojs-contrib-hls.js 7:490-497`

I think the warning came from this line: https://github.com/surmon-china/vue-video-player/blob/master/player.vue#L60

**Comment by F-loat** [comment]
在webpack的配置文件里加入 `noParse: [/videojs-contrib-hls/],`

**Comment by ParadeTo** [comment]
按照该方法（在webpack的配置文件里加入 noParse: [/videojs-contrib-hls/]）进行了设置后又有新的问题：
videojs-contrib-hls.js?0a95:19 Uncaught ReferenceError: require is not defined

**Comment by F-loat** [comment]
这行代码你有修改吗
``` javascript
if (configs.hls) require('videojs-contrib-hls/dist/videojs-contrib-hls.js')
```

**Comment by ParadeTo** [comment]
没动过啊

**Comment by F-loat** [comment]
我试了下没问题的啊，你用的webpack是哪个版本

**Comment by ParadeTo** [comment]
"webpack": "^1.13.2",
    "webpack-dev-middleware": "^1.8.3",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1"

**Comment by F-loat** [comment]
https://github.com/F-loat/vod/blob/master/vod-client/build/webpack.base.conf.js#L37
你是这么加入的不

**Comment by F-loat** [comment]
另外webpack2不修改配置也不会报错，不行的话你可以升级webpack的版本试试

**Comment by ParadeTo** [comment]
谢谢，打算先用h5的video算了，以后有需要再折腾

**Comment by F-loat** [comment]
嗯，没事，videojs相关的库好多现在对webpack都还不太友好，以后也会改善的应该

**Comment by hefeng1208** [comment]
@F-loat hello 我用videojs-contrib-hls这个地时候，遇到了这个错，请问你有遇到过吗？

XMLHttpRequest cannot load http://live-play-hls.jcloudcs.com/live/30905e998377b5dad9.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3333' is therefore not allowed access.

**Comment by F-loat** [comment]
这个是跨域的问题，你配置下转发或者用自己服务器的视频文件就可以了

**Comment by simmzl** [comment]
@F-loat @ParadeTo  noParse 是不进行压缩和扫描依赖，但是videojs-contrib-hls.js依赖video.js，所以运行时videojs-contrib-hls.js里的require(video.js)会报错require is not defined

**Comment by surmon-china** [comment]
最新版组件 v5.0.0 配合最新版 hls 解决此问题，等待发布。

**Comment by Believel** [comment]
![image](https://user-images.githubusercontent.com/22617170/42124503-25fb163a-7c96-11e8-8300-e020c74c7578.png)
打包之后点击视频报那个错误，在moude中添加了 noParse: [/videojs-contrib-hls/]但是还没有起作用

**Comment by DiaoFromHappyValley** [comment]
> @F-loat @ParadeTo noParse 是不进行压缩和扫描依赖，但是videojs-contrib-hls.js依赖video.js，所以运行时videojs-contrib-hls.js里的require(video.js)会报错require is not defined

那这个问题咋解决啊，老哥
