### ISSUE TITLE
playbackRates倍速在安卓上不显示

### ISSUE THREAD

**Issue by xzzfxz** [surmon-china/vue-video-player#344]
1.在移动端使用时（我是在微信公众号中使用的），在安卓手机上，倍速选项会隐藏。在Ios上没问题。不知道是什么情况。
2.在全屏播放时能显示倍速选项吗？（全屏下，安卓和ios都没有倍速选项）

**Comment by zhangmingli-com** [comment]
您好,这个问题解决了吗?如果解决了,请问一下是怎么解决的

**Comment by xzzfxz** [comment]
> 您好,这个问题解决了吗?如果解决了,请问一下是怎么解决的

时间有点长了，好像是换了个插件

**Comment by zhangmingli-com** [comment]
好的,谢谢
