### ISSUE TITLE
Unable to get video src to display in Nuxt

### ISSUE THREAD

**Issue by daletom** [surmon-china/vue-video-player#356]
vue.js version 2.12

You can see it live here: https://www.thedales.me/video/

The page is blank, unable to get src to display when I inspect front end. Here is a screen shot: 
![image](https://user-images.githubusercontent.com/13734256/81468763-698a1380-9196-11ea-859e-b0e466ef3537.png)

Was expecting to see a .m3u8 video or even the player showing some kind of error. Here is the template I am using:
```
<template>
  <section class="container">
    <video-player
      v-video-player:myVideoPlayer="playerOptions"
      class="video-player-box"
      :playsinline="playsinline"
      @play="onPlayerPlay($event)"
      @pause="onPlayerPause($event)"
      @ended="onPlayerEnded($event)"
      @loadeddata="onPlayerLoadeddata($event)"
      @waiting="onPlayerWaiting($event)"
      @playing="onPlayerPlaying($event)"
      @timeupdate="onPlayerTimeupdate($event)"
      @canplay="onPlayerCanplay($event)"
      @canplaythrough="onPlayerCanplaythrough($event)"
      @ready="playerReadied"
      @statechanged="playerStateChanged($event)"
    ></video-player>
  </section>
</template>

<script>
export default {
  data() {
    return {
      playsinline: true,
      playerOptions: {
        muted: false,
        controls: true,
        language: 'en',
        playbackRates: [0.7, 1.0, 1.5, 2.0],
        sources: [
          {
            type: 'application/x-mpegURL',
            src:
              'https://stream.mux.com/GvgMD02G02mv0200fDiP71cLF9RrbRlEq8V9.m3u8',
            poster:
              'https://images.mux.com/GvgMD02G02mv0200fDiP71cLF9RrbRlEq8V9/thumbnail.jpg'
          }
        ]
      }
    }
  },
  mounted() {
    // console.log('this is current player instance object', this.myVideoPlayer)
  },
  methods: {
    onPlayerPlay(player) {
      // console.log('player play!', player)
    },
    onPlayerPause(player) {
      // console.log('player pause!', player)
    },
    onPlayerEnded(player) {
      // console.log('player ended!', player)
    },
    onPlayerLoadeddata(player) {
      // console.log('player Loadeddata!', player)
    },
    onPlayerWaiting(player) {
      // console.log('player Waiting!', player)
    },
    onPlayerPlaying(player) {
      // console.log('player Playing!', player)
    },
    onPlayerTimeupdate(player) {
      // console.log('player Timeupdate!', player.currentTime())
    },
    onPlayerCanplay(player) {
      // console.log('player Canplay!', player)
    },
    onPlayerCanplaythrough(player) {
      // console.log('player Canplaythrough!', player)
    },
    playerStateChanged(playerCurrentState) {
      // console.log('player current update state', playerCurrentState)
    },
    playerReadied(player) {
      // console.log('example 01: the player is readied', player)
    }
  }
}
```

I've also done this in the plugins: 
import Vue from 'vue'

const VueVideoPlayer = require('vue-video-player/dist/ssr')
Vue.use(VueVideoPlayer)

and I believe I included it correctly in my nuxt.config:
![image](https://user-images.githubusercontent.com/13734256/81468809-afdf7280-9196-11ea-930e-81b22e51d3bc.png)
 

Any advice greatly appreciated!

**Comment by daletom** [comment]
I've added it to github so you can review there as well: https://github.com/daletom/dalesiteV2/blob/master/pages/video/index.vue

Been trying for last 5 days and maybe made some progress, I can easily make mp4/webm work, but for HLS it just shows "no compatible source was found for this media".  I feel like an extra set of eyes might find the small thing I am messing up. Thanks!

![Screen Shot 2020-05-13 at 2 51 56 PM](https://user-images.githubusercontent.com/13734256/81869739-6a6dcd00-9529-11ea-8e59-e937538c9c72.png)

**Comment by Mjavala** [comment]
Any progress on this?

**Comment by peyc5** [comment]
did you fix it?

**Comment by Nabute** [comment]
I ran into this issue a few days ago and fixed it by using installing Video-js 7 and used the builtin HTML5 player.[Take a look at this gist](https://gist.github.com/Nabute/2454d20a4c2cd1683e9339049d9ae96d)

**Comment by daletom** [comment]
@Nabute Still getting that error

![image](https://user-images.githubusercontent.com/13734256/93810219-8c7c0800-fc0b-11ea-839f-edd21721f7e7.png)

here you can see the differences I did in a separate video branch to match your gist: https://github.com/daletom/dalesiteV2/compare/video

Any idea what else it could be?

**Comment by Nabute** [comment]
@daletom What's the version of your VideoJs?

**Comment by daletom** [comment]
7.8.4

**Comment by daletom** [comment]
Thanks for sending that @Nabute . Is the example even using the Vue-Video-Player?  Yes, your example absolutely works. But I guess this Vue-Video-Player isnt very easy to use, thats for sure. Thanks for all the help.
