### ISSUE TITLE
This dependency was not found:  mux.js/lib/mp4/caption-parser

### ISSUE THREAD

**Issue by Anne3720** [surmon-china/vue-video-player#359]
This dependency was not found:

* mux.js/lib/mp4/caption-parser in ./node_modules/videojs-flash/node_modules/video.js/dist/video.es.js

To install it, you can run: npm install --save mux.js/lib/mp4/caption-parser

In my develop enviroment, if I use "yarn  intsall" command, this error always happen.  but if i use "npm install", this file will exist.  Recently, in my production enviroment(use jenkins), it is "npm install", this error happens too.

**Comment by abrantes01** [comment]
@Anne3720 did you find any solution about your issue ?
