### ISSUE TITLE
拉流时关闭页面无法销毁组件

### ISSUE THREAD

**Issue by useryechen** [surmon-china/vue-video-player#384]
### 版本
- vue 2.6.11
- vue-video-player 5.0.2

### 问题描述
使用vue-video-player在弹窗组件中，通过`comouted`配置`options`，进行拉流播放，播放没有问题。但是在关闭弹窗时，在`beforeDestroy`中调用`this.$refs.videoPlayer.dispose()`进行组件销毁，发现弹窗关闭后，还在拉流。之前试过好几个播放器了，`dplayer`、`hls.js`、`video.js`都没有成功销毁，还在一直拉流。麻烦遇到过的前辈分析一下问题出在哪儿

**Comment by mianyansanshengsanshi** [comment]
我在用dash.js的时候也遇到了，请问现在解决了吗

**Comment by useryechen** [comment]
> 我在用dash.js的时候也遇到了，请问现在解决了吗

最后用的`dplayer`和`hls`，因为涉及到播放拉流呢。在播放组件的`beforeDestroy`中先把实例化的`hls`调用`destroy`销毁掉，然后再将实例化出来的`dplayer`对象也调用`destroy`销毁掉。我看`network`中就不再拉流了

**Comment by mianyansanshengsanshi** [comment]
> > 我在用dash.js的时候也遇到了，请问现在解决了吗
> 
> 最后用的`dplayer`和`hls`，因为涉及到播放拉流呢。在播放组件的`beforeDestroy`中先把实例化的`hls`调用`destroy`销毁掉，然后再将实例化出来的`dplayer`对象也调用`destroy`销毁掉。我看`network`中就不再拉流了

谢谢，原来unmount改成了destroy，我也用beforeDestroy这个回调解决了
