### ISSUE TITLE
是否有基于es6开发的计划？

### ISSUE THREAD

**Issue by chenzhutian** [surmon-china/vue-video-player#39]
请问作者有考虑过用es6来开发，然后webpack编译成es5发布么？
这样别人可以直接引用es6的源码，就可以利用webpack2的tree shaking来减体积；也可以直接引用dist下的es5代码

**Comment by surmon-china** [comment]
后续支持，感谢反馈

**Comment by surmon-china** [comment]
v3.0.0 fix  it.
