### ISSUE TITLE
iOS设备，微信内置浏览器播放自动全屏问题。

### ISSUE THREAD

**Issue by ritayzy** [surmon-china/vue-video-player#4]
你好，这个播放器在微信播放会自动全屏，我在 

[第三行](https://github.com/surmon-china/vue-video-player/blob/master/player.vue#L3)
https://github.com/surmon-china/vue-video-player/blob/master/player.vue#L3

变成下面的代码

```
<video class="video-js vjs-custom-skin" :class="{ 'live': options.live }" webkit-playsinline="true"></video>
```

就可以解决在微信浏览器里面播放自动全屏的问题

第二种方式，通过选项的方式设置属性，
我在`player.vue`的`185`行

[第185行](https://github.com/surmon-china/vue-video-player/blob/master/player.vue#L185)
https://github.com/surmon-china/vue-video-player/blob/master/player.vue#L185

加入下面的代码，也可以解决问题

```
        var playsinline = options.playsinline !== undefined ? options.playsinline : true;
        this.player.el().firstChild.setAttribute('webkit-playsinline', playsinline);
```

这两种方式都是给`video`这个标签加上一个`webkit-playsinline`属性，能不能在库里面添加一个这个啊？

可以看一下啊，谢谢了~ @surmon-china

**Comment by surmon-china** [comment]
可以的

**Comment by surmon-china** [comment]
测试无兼容问题后，即更新

**Comment by ritayzy** [comment]
好的，thank you~

**Comment by surmon-china** [comment]
已更新
