### ISSUE TITLE
Cannot resolve module 'videojs'

### ISSUE THREAD

**Issue by peakcary** [surmon-china/vue-video-player#40]
./~/videojs-youtube/dist/Youtube.js
Module not found: Error: Cannot resolve module 'videojs' in  /node_modules/videojs-youtube/dist
resolve module videojs in  /node_modules/videojs-youtube/dist

**Comment by stsking** [comment]
@peakcary   I have the same issue, do you resolve that? thanks.

**Comment by surmon-china** [comment]
v3.0.0 fix  it.
