### ISSUE TITLE
In video.js, when the source content type is "audio/mp3", the subtitle of the track is not updated.

### ISSUE THREAD

**Issue by iranika** [surmon-china/vue-video-player#443]
### Describe the bug

I am trying to add subtitles to audio.
In video.js, when the source content type is "audio/mp3", the subtitle of the track is not updated.

We have prepared a Demo page.

Demo page.
https://iranika.github.io/videojs-debug/

Souce Code.
https://github.com/iranika/videojs-debug

What is interesting is that when you change the caption or operate the fullscrean, the subtitle will be displayed.
However, the subtitle is not updated.
It's not detecting the `cuechange` Event, i think well...

Is this a bug?

### Reproduction

Demo page.
https://iranika.github.io/videojs-debug/

Souce Code.
https://github.com/iranika/videojs-debug

### System Info

```shell
vanilla. using CDN.
I am not use package manager.
```

### Used Package Manager

yarn

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by iranika** [comment]
sorry, mistake.

**Comment by surmon-china** [comment]
Hi @iranika, this is actually an issue with [Video.js](https://github.com/videojs/video.js/issues/7910).

In fact, after my testing, I found that the subtitles do have the problem of not updating, and it should be related to an event inside Video.js.

**Comment by iranika** [comment]
Hi @surmon-china , thank you for testing.

I have created an issue on video.js.
https://github.com/videojs/video.js/issues/7910

I will continue to wait for this bug to be fixed.

**Comment by iranika** [comment]
This problem was fixed PR(https://github.com/videojs/video.js/pull/7918), and merged v7.20.3 🎉
