### ISSUE TITLE
Video.js Vimeo plugin does not work.

### ISSUE THREAD

**Issue by Axisv** [surmon-china/vue-video-player#45]
<img width="647" alt="screen shot 2017-03-17 at 17 12 07" src="https://cloud.githubusercontent.com/assets/12220618/24049501/f0ce6ab2-0b34-11e7-96b0-910fbc52b167.png">
Any fixes?

**Comment by surmon-china** [comment]
As the Vimeo package support for npm is not perfect, this feature is temporarily deleted.
