### ISSUE TITLE
Space key not pause the video

### ISSUE THREAD

**Issue by Evlos** [surmon-china/vue-video-player#46]
#### Reproduction Link
- https://surmon-china.github.io/vue-video-player/

#### Steps to reproduce
1. Play the video
2. Go fullscreen
3. Press space key
4. It exits fullscreen

#### What is Expected?		
4. Video pauses

#### What is actually happening?
4. It exits fullscreen

**Comment by Evlos** [comment]
this might help:
https://github.com/videojs/video.js/pull/3032

**Comment by surmon-china** [comment]
Thanks for feedback, i am trying to fix it.

**Comment by surmon-china** [comment]
After testing, you can use the [videojs-hotkeys](https://github.com/ctd1500/videojs-hotkeys) plugin to implement hotkey listening, it looks good work, the case code can be seen [here](https://github.com/surmon-china/vue-video-player/blob/master/examples/02-video.vue),
Hotkey requires the player to be in the focus state to take effect, and wish you a happy one!

**Comment by caoruiy** [comment]
The above answers helped me solve the control problem, but after testing, the problem still exists in Firefox. My fix is to add an event handler to the space key. If you have any questions, you can correct me.

CN: 上面的解答帮助我解决了控件问题，但是经过测试，在火狐浏览器下，依然存在问题，我的修复方法是在空格按键上增加一个事件处理。就像下面这样，看起来没啥毛病。

```
playerIsReady(player) {
      player.hotkeys({
        volumeStep: 0.1,
        seekStep: 5,
        enableModifiersForNumbers: false,
        // 强制使用热键来控制，即便当前空间获得焦点
        alwaysCaptureHotkeys: true,
        playPauseKey: function(event, player) {
          // FIXED: 在FF中，如果当前播放器全屏，防止空格键切换全屏
          // FIXED: In FF, if the current player is full screen, prevent the space bar from switching to full screen
          if (player.isFullscreen()) {
            player.el().focus()
          }
          // Space bar or MediaPlayPause
          return event.which === 32 || event.which === 179
        },

        fullscreenKey: function(event) {
          // override fullscreen to trigger when pressing the F key or Ctrl+Space
          return event.which === 70
        }
      })
    }
```
