### ISSUE TITLE
无法编译webpack出错

### ISSUE THREAD

**Issue by lovesxw** [surmon-china/vue-video-player#49]
错误信息
`/~/video.js/dist/video-js.css
Module parse failed: /Users/ash/Documents/b/node_modules/video.js/dist/video-js.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .video-js .vjs-big-play-button:before, .video-js .vjs-control:before, .video-js .vjs-modal-dialog, .vjs-modal-dialog .vjs-modal-dialog-content {
|   position: absolute;
|   top: 0;
 @ ./~/vue-video-player/index.js 9:0-37
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js`

**Comment by surmon-china** [comment]
#16
