### ISSUE TITLE
Player flashes frames and doesn't play type=rtmp/mp4 VOD

### ISSUE THREAD

**Issue by AaronMorgan** [surmon-china/vue-video-player#57]
Hi, video.js supports rtmp VOD playback, but when I use vue-video-player the player loads the first frame of the stream and flickers back and forth between black and frame, continually. It seems to have pulled down correct duration information.

video.js example that works:

` <video id="example" class="video-js vjs-default-skin vjs-big-play-centered" controls preload="auto" width="640" height="264"
    data-setup='{"techOrder": ["html5", "flash"]}'>
    <source src="rtmp://[serveraddress]/vod/mp4:sample.mp4" type='rtmp/mp4' />
  </video>`

This is what I've done with vue-video-player:

`<app-vue-video-player :options="{ sources: [{src: 'rtmp://[serveraddress]/vod/mp4:sample.mp4', type: 'rtmp/mp4'}] }"></app-vue-video-player>`

I've tested type=video/mp4 streams and they playback fine.

**Comment by surmon-china** [comment]
http://stackoverflow.com/questions/33940721/stream-video-with-rtmp-and-videojs

**Comment by surmon-china** [comment]
@AaronMorgan Update to v3.0.9 please, it should be work!
```javascript
videoOptions: {
  autoplay: true,
  sources: [{
    type: "rtmp/mp4",
    src: 'rtmp://r.demo.flowplayer.netdna-cdn.com/play/&mp4:vod/demo.flowplayer/buffalo_soldiers.mp4'
  }]
}
```

**Comment by AaronMorgan** [comment]
@surmon-china Thank you.
