### ISSUE TITLE
videoOptions is not defined , ssr.js

### ISSUE THREAD

**Issue by SzHeJason** [surmon-china/vue-video-player#58]
![image](https://cloud.githubusercontent.com/assets/20609396/26026793/e5134ddc-3834-11e7-8d97-302c78726bb5.png)
![image](https://cloud.githubusercontent.com/assets/20609396/26026807/109b1868-3835-11e7-8e8c-2df5fd65ae66.png)

**Comment by surmon-china** [comment]
Update to v3.1.0, it should be work!

**Comment by SzHeJason** [comment]
@surmon-china 还有一个bug 使用 ssr.js 在 videoJs初始化 的时候，由于参数是通过vue绑定进去的，所以object对象有 只读的__ob__ 属性，但是在videoJs内部读取参数的时候会去读 __ob__ 属性，并且把它当成一个正常的属性调用，见下图

**Comment by SzHeJason** [comment]
![image](https://cloud.githubusercontent.com/assets/20609396/26027450/c75a3ede-3840-11e7-81d2-cdae4ef0c55d.png)
![image](https://cloud.githubusercontent.com/assets/20609396/26027474/01ef5386-3841-11e7-9827-59e8f2390d4f.png)
![image](https://cloud.githubusercontent.com/assets/20609396/26027477/0f8007b6-3841-11e7-9bb8-2174314c2f9e.png)

**Comment by surmon-china** [comment]
@SzHeJason 已优化！
