### ISSUE TITLE
希望升级video js 的版本

### ISSUE THREAD

**Issue by ibmsoft** [surmon-china/vue-video-player#59]
目前video js 的版本是5.x，希望升级到 6.x 系列

**Comment by surmon-china** [comment]
可以提交下PR呀

**Comment by jiayouwyhit** [comment]
请问如何在一开始就把最下面一行的所有控制按钮都显示出来啊？

**Comment by surmon-china** [comment]
@ibmsoft 已升级
@jiayouwyhit https://stackoverflow.com/questions/13384276/videojs-keep-controls-visible

**Comment by surmon-china** [comment]
@ibmsoft 6.0有不兼容更新，等到有时间，我再做完备的升级

**Comment by jiayouwyhit** [comment]
@surmon-china Thanks a lot.
[](https://stackoverflow.com/questions/13384276/videojs-keep-controls-visible)
This link works perfectly!

**Comment by surmon-china** [comment]
请升级到v4.0.0。
