### ISSUE TITLE
youtube 资源国内无法请求的问题

### ISSUE THREAD

**Issue by ritayzy** [surmon-china/vue-video-player#6]
您好，这段代码能不能根据条件来选择添加

[youtube](https://github.com/surmon-china/vue-video-player/blob/master/index.js#L9)
https://github.com/surmon-china/vue-video-player/blob/master/index.js#L9

有了这段代码，我发现请求一个`youtube`的资源文件[iframe_api](https://www.youtube.com/iframe_api),

![image](https://cloud.githubusercontent.com/assets/18484770/19512981/f1157c7e-9620-11e6-91dd-905cc7a3f8ea.png)

而在国内，你懂的，根本无法访问啊，会造成浏览器一直加载中的状态。

谢谢啦~

**Comment by surmon-china** [comment]
好的，稍后处理...

**Comment by surmon-china** [comment]
已修复
