### ISSUE TITLE
真的不打算弄个中文文档吗？

### ISSUE THREAD

**Issue by yk5tc** [surmon-china/vue-video-player#63]
用的人大多数都是国人吧，英文文档看得真累

**Comment by surmon-china** [comment]
英文阅读能力应该是你的基本水平

**Comment by yk5tc** [comment]
文档是给人看的，不是用来装逼的。
外国程序员弄出个什么框架之类的，人家可不在乎非得去弄个中文文档，反倒是国内的这些所谓的大神，为了显示自己的东西高大上，故意弄个英文文档，喧哗取宠罢了

**Comment by surmon-china** [comment]
请君自便

**Comment by lihsai0** [comment]
那你去用易语言编程吧，js都是英文的关键字不适合你。

**Comment by bestvow** [comment]
@yk5tc 文档作为一种基础教程的存在,就算是英文的也会采用最通俗易懂的语言描述.如果依然看不懂,可能自身原因更多
