### ISSUE TITLE
[Vue warn]: Failed to resolve directive: video-player  (found in <Anonymous>)

### ISSUE THREAD

**Issue by SidFeng** [surmon-china/vue-video-player#64]
i am use vue-server-renderer to ssr,so  How to use in ssr?  I am always show this error.

**Comment by surmon-china** [comment]
1. https://github.com/surmon-china/vue-video-player#vue-mount
2. https://github.com/surmon-china/vue-video-player#use-in-ssr

**Comment by SidFeng** [comment]
I use it as vue-mount ,but it is show this error.
![image](https://user-images.githubusercontent.com/6702354/27265975-2dab3b2a-54cf-11e7-8a9c-7a2c5df70b06.png)
![image](https://user-images.githubusercontent.com/6702354/27265986-4d403c10-54cf-11e7-9485-fc79674c8483.png)

**Comment by surmon-china** [comment]
```javascript
require('vue-video-player/ssr')
```


Ssr!

**Comment by SidFeng** [comment]
Sorry，it is not wok.

**Comment by SidFeng** [comment]
I fix it by myself.
```
const inBrowser = typeof window !== 'undefined'
  if (inBrowser) {
    require('video.js/dist/video-js.css')
    Vue.use(require('vue-video-player/ssr'))
  }
```

**Comment by surmon-china** [comment]
![image](https://user-images.githubusercontent.com/14019524/27273866-74bd3b9c-5503-11e7-80ad-0b6e4e3c01df.png)

**Comment by Timnny** [comment]
import Vue from 'vue'

if (process.BROWSER_BUILD) {
	const VueVideoPlayer = require('vue-video-player/ssr')
	Vue.use(VueVideoPlayer)
}

warn: 
vue.runtime.esm.js:430 [Vue warn]: Failed to resolve directive: video-player

(found in <D:\GitH5Sdk\wuliList\wuliListNuxtVideoPlayer\pages\video\index.vue>)
