### ISSUE TITLE
VIDEOJS: ERROR: TypeError: this.el_.vjs_getProperty is not a function

### ISSUE THREAD

**Issue by An0nymous0** [surmon-china/vue-video-player#67]
查看之前的issues说升级到3.0，  目前使用版本3.1.1 

步骤：
1.播放视频
2.切换vue路由

控制台一直会提示VIDEOJS: ERROR: TypeError: this.el_.vjs_getProperty is not a function

**Comment by surmon-china** [comment]
最新版`v3.1.4`会遇到这个问题吗？

**Comment by terevor** [comment]
@surmon-china v4.0.4还是有同样的问题，出现的前提条件是techOrder: ['flash', 'html5']，优先使用flash播放，vue路由切换触发player.vue中的beforeDestroy，chrome下一切正常，但是chromium内核（版本55.0.2883.87）其他浏览器都会报错，（低版本ff也会报，升级新版本后恢复正常）。debug后发现执行this.player.pause()会引发videojs-flash.es.js中一系列报错，查看videojs-flash.es.js源码发现dispose方法前有一句注释：

> noop for native source handler dispose, as cleanup will happen automatically.

所以我理解为使用flash tech不需要手动去调用pause，修改player.vue中的beforeDestroy，加if判定如下：
`if (this.player.techName_ !== 'Flash'  && this.player.pause) {
  this.player.pause()
}`
以上修改后问题解决
