### ISSUE TITLE
在nuxt框架下，插件不能正常运行

### ISSUE THREAD

**Issue by Hades-li** [surmon-china/vue-video-player#70]
### 在nuxt框架下，插件不能正常运行。
按照nuxt-ssr-example中的代码执行，报
TypeError: Cannot convert undefined or null to object。
然后我发现
```
mounted() {
    console.log('this is current player instance object', this.myVideoPlayer)
}
```
这段代码中，this.myVideoPlayer显示为undefined。猜测可能就是插件在注册自定义指令时失败了。于是我看了ssr.js的源码发现。
```
inserted: function (el, binding, vnode) {
...
  delete options.plugins.__ob__ //plugins显示为undefined，从而导致代码报错，不能继续。
...
}
```
于是将代码修改为
```
if (options.plugins) {
  delete options.plugins.__ob__
}
```
就可以正常运行了。但这样的修改可能会导致其它的bug或是在spa环境下的报错。

**Comment by surmon-china** [comment]
可能导致的其他bug有哪些？

**Comment by Hades-li** [comment]
还没测试有哪些

**Comment by surmon-china** [comment]
提交个PR吧，ssr.js 和 spa 里都要改，版本号末尾数更新为最近偶数。

**Comment by Timnny** [comment]
[Vue warn]: Failed to resolve directive: video-player
