### ISSUE TITLE
使用官方hls的例子，报错videojs-contrib-hls.js?0bd9:3559 Uncaught TypeError: Cannot read property 'EventTarget' of undefined

### ISSUE THREAD

**Issue by acodercat** [surmon-china/vue-video-player#78]
使用官方的hls的例子，报错videojs-contrib-hls.js?0bd9:3559 Uncaught TypeError: Cannot read property 'EventTarget' of undefined

**Comment by syn6699** [comment]
使用官方的hls的例子，报错videojs-contrib-hls.js?0bd9:3559 Uncaught TypeError: Cannot read property 'EventTarget' of undefined

**Comment by struts2012** [comment]
@syn6699  'EventTarget' of undefined 问题解决了吗

**Comment by surmon-china** [comment]
最新版组件 v5.0.0 已解决此问题，查看 CHANGELOG.md

**Comment by acodercat** [comment]
感谢
