### ISSUE TITLE
Issue with license

### ISSUE THREAD

**Issue by vladimyr** [surmon-china/vue-video-player#79]
I'm curious, is there any particular reason why you chose GPL license over more permissive MIT one? Doing so you prevented commercial usage of package, is that intended?
Do you mind adding MIT through dual licensing a-la jszip?

**Comment by surmon-china** [comment]
ok

**Comment by vladimyr** [comment]
I'll assume that means you'll follow my suggestion :thinking: 
Anyway, thank you for quick response and keep up doing good work by continuing building useful Vue components :+1: :1st_place_medal:

**Comment by vladimyr** [comment]
Thank you very much for resolving this :+1: :100:
