### ISSUE TITLE
想修改video标签的class，还有就是想从后台读取多个video的时候不方便

### ISSUE THREAD

**Issue by acodercat** [surmon-china/vue-video-player#80]
想修改video标签的class，还有就是想从后台读取多个video的时候不方便

**Comment by surmon-china** [comment]
后半句详细描述下

**Comment by acodercat** [comment]
我想ajax请求多个播放窗口，这样的话，好像不能实现。因为是用options来读取配置信息的。感谢。不知道我说的清楚不

**Comment by acodercat** [comment]
折腾了半天，也看了源码

**Comment by acodercat** [comment]
感谢回答下

**Comment by surmon-china** [comment]
写个函数，把公共部分抽离，每次根据不同的地址返回不同的配置不就完了，组件也支持`v-for`的啊，传入属性也支持函数的啊，怎么会有实现不了的东西呢

**Comment by acodercat** [comment]
谢谢，麻烦再问一下修改class呢

**Comment by surmon-china** [comment]
直接在组件上加class就行了

**Comment by acodercat** [comment]
我加了video.js自带的样式vjs-4-3不行，比如我要修改video样式，不适用vjs-custom-skin，也不行

**Comment by surmon-china** [comment]
是不是加了`scoped`了

**Comment by acodercat** [comment]
我只是在style上面使用了scoped，我去掉了也不行，求助

**Comment by acodercat** [comment]
```
:options="playerOptions(link)"
```
这个函数返回配置，好像不行

**Comment by surmon-china** [comment]
这，这个问题什么时候关的...

**Comment by surmon-china** [comment]
样式问题解决了吗？

**Comment by hugselina2019** [comment]
> 样式问题解决了吗？

样式问题估计是楼上的老哥没有 import 'vue-video-player/src/custom-theme.css'
还就是这个css貌似不太兼容 因为业务需要每次都要铺满video所在的dom, 所以每次使用都要自己去modules里面找到 custom-theme.css然后修改。有点点麻烦
