### ISSUE TITLE
 RTMP streaming video cannot be played

### ISSUE THREAD

**Issue by Chenjiayuan195** [surmon-china/vue-video-player#81]
> export default {
    data() {
      return {
        playerOptions: {
          start: 0,
          playsinline: false,
          muted: true,
          language: 'en',
          autoplay:true,
          sources: [{
            type: "rtmp/mp4",
            src: "rtmp://172.29.4.135:12966/live/realmontior;channel=1;subtype=0"
          }]
         }
      }
    }

no video played and the console didn't make any mistakes,but this RTMP can get by the  Flash Media Server 3.5

**Comment by surmon-china** [comment]
Update to v4.0.0 please, you will see the example for rtmp.

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-video-player/blob/master/examples/05-video.vue
