### ISSUE TITLE
after importing vue-video-player, npm run dev, it reports error

### ISSUE THREAD

**Issue by wecker** [surmon-china/vue-video-player#83]
[Vue warn]: Failed to mount component: template or render function not defined.

I looked around on google and find out it's because the vue-video-player module I got is runtime-only version, not standalone version...

how could I get a standalone version?
and how can I use this runtime version if there's no standalone one?

Thanks!

**Comment by surmon-china** [comment]
I'm sorry, I do not understand what you mean by the standalone version, what is its use scene?

**Comment by wecker** [comment]
Thank you for replying!
I don't know why, I just run npm install --save vue-video-player and I'm importing it like this:
![image](https://user-images.githubusercontent.com/5844088/29266017-b7e448c8-8115-11e7-936b-0f89345edf22.png)

and then the video player is not showing and when I check the console of the browser, it reports 
[Vue warn]: Failed to mount component: template or render function not defined.
found in

---> <VueVideoPlayer>
       <VideoPlay> at /Users/HOZ/Projects/vue_epg_op_service/src/components/VideoPlay.vue


I'm using Vue2 + vuex + webpack3.4.1

**Comment by surmon-china** [comment]
Please read the README.md documentation carefully, if you are not serious enough, no one can help you!

**Comment by wecker** [comment]
so sorry about that! I'm new to frontend and Vue, so I don't know what's wrong with my code. I read the readme over and over, one thing I have to point out, import { videoPlayer } from 'vue-video-player' doesn't work, I have to remove '{' and '}' so that vue can recognize this component.
    could you please kindly point out what's wrong with my code? Thanks a lot!

**Comment by surmon-china** [comment]
1. global use
```javascript
import Vue from 'vue'
import VueVideoPlayer from 'vue-video-player'
Vue.use(VueVideoPlayer)
```

2. component use
```javascript
import { videoPlayer } from 'vue-video-player'
export default {
  components: {
    videoPlayer
  }
}
```

**Comment by wecker** [comment]
Thank you and it's amazing that it works, although the layout is a mass but I think I can work it out!
I thought if I named the component as VueVideoPlayer and use the tag <vue-video-player> is certainly ok, but it's not!!!  I don't know why.... , and what does { } do when "import { videoPlayer } from 'vue-video-player" ?  what's the difference between the import without {}?
Could you explain to me? 
Thank you very much!
