### ISSUE TITLE
Strange error when initializing component

### ISSUE THREAD

**Issue by kerf007** [surmon-china/vue-video-player#85]
Component version: v4.0.2
Hello, when I init component i see in browser console following error:

![](http://i.imgur.com/jp8ievP.png)
![](http://i.imgur.com/O3YCAIr.png)
If I little change code of your component then everything works fine:
![](http://i.imgur.com/24B7DWT.png)

But It looks very strange...

**Comment by surmon-china** [comment]
You can according to their own to submit a pr! welcome.

**Comment by kerf007** [comment]
Ok, but I don't understand why... Your code looks right but browser shows the error.

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-video-player/blob/master/src/player.vue#L126
https://github.com/surmon-china/vue-video-player/blob/master/ssr.js#L108

**Comment by roberttolton** [comment]
I'm also getting this error, though it didn't happen initially. I've only noticed it showing the error since I installed my project on another Mac to work on it.

**Comment by surmon-china** [comment]
Update to v4.0.3 please.
