### ISSUE TITLE
Best way to use videojs-youtube?

### ISSUE THREAD

**Issue by Spoowy** [surmon-china/vue-video-player#88]
Hi all,

what is the best way to use this: https://github.com/videojs/videojs-youtube ?

I tried importing it like any other Vue package but nada.. it's not working. I get the usual unsupported media error from videojs, as if videojs-youtube is not loaded at all.

Has anyone pulled this off successfully so far?

Cheers,
Erwin

**Comment by surmon-china** [comment]
`Videojs-youtube` and the latest version of videojs 6.2 are not compatible, if you want to use` videojs-youtube`, please go back to `vue-video-player` v3.1.4.

**Comment by Spoowy** [comment]
Thanks @surmon-china. You saved my life.
