### ISSUE TITLE
video snapshot Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by buildJava** [surmon-china/vue-video-player#89]
when I want to make a video snapshot by using canvs.toDataURL, there is the problem 'Tainted canvases may not be exported.' which is because of browser "crossOrigin='anonymous'" ,so I suggest add crossOrigin='anonymous' in player.vue video tag

**Comment by surmon-china** [comment]
ok.

**Comment by surmon-china** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTML/CORS_enabled_image

**Comment by surmon-china** [comment]
`video.crossOrigin = "Anonymous";`

**Comment by surmon-china** [comment]
v5.0.0 fix it.
