### ISSUE TITLE
playerStateChange not called due to case issue.

### ISSUE THREAD

**Issue by MichMich** [surmon-china/vue-video-player#9]
`playerStateChange` event is not called because of this issue: https://github.com/vuejs/vue/issues/4044

Is there a workaround for this issue?

**Comment by surmon-china** [comment]
1.0 or 2.0?

**Comment by surmon-china** [comment]
1.0:

```javascript
events: {
   playerStateChanged: function(state) {  ...  }
}
```

2.0

```html
<video-player :options="videoOptions" @playerStateChanged="playerStateChanged"></video-player>
```

```javascript
methods: {
   playerStateChanged: function(state) {  ...  }
}
```

**Comment by MichMich** [comment]
Sorry for the slow response. The issue is with Vue 3. (See link in openings issue). I made a fork of the project in which i changed the event name from `playerStateChanged` to `state`, en then used the following line:

```
<video-player :options="videoOptions" @state="playerStateChanged"></video-player>
```

It turns out Vue 2 does not understand camelCase or snake_case names as custom events.

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-video-player/blob/master/player.vue#L156
https://github.com/surmon-china/vue-video-player/blob/master/player.vue#L157

In vue, the child component sends an event to the parent component, whose event name is defined in the child component;
In 2.0, the parent component listens for custom events defined by subcomponents by using the @ character at the subcomponent's call, so you should understand that you are not able to determine the name of the event that the subcomponent propagated up, You can change the name of the parent component's method, such as:

```vue
<video-player :options="videoOptions" @playerStateChanged="myFunctionForVideo"></video-player>

methods: {
   myFunctionForVideo: function(state) {  ...  }
}
```

**Comment by MichMich** [comment]
I'm very well aware of this. But please read this issue: https://github.com/vuejs/vue/issues/4044

**Comment by cjcrawford** [comment]
From the issue on VueJS you could probably fix temporary by using a string component template for rendering the video component.

**Comment by MichMich** [comment]
Yeah, but that feels a bit like a workaround. Hoped that there was some sort of official fix. Thanks for the suggestion though.
