### ISSUE TITLE
播放视频黑屏

### ISSUE THREAD

**Issue by wlinshicong** [surmon-china/vue-video-player#91]
1.在ios平台上，播放本地视频没问题，换成在线链接就不行，官网的https://cdn.theguardian.tv/webM/2015/07/20/150716YesMen_synd_768k_vp8.webm 地址也播放不了，安卓平台可以正确播放

**Comment by richaryau** [comment]
同样的问题。
不过我在IOS上safari和Chrome都是正常的。但微信里却不行。

提示：“VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. MediaError {code: 4, message: "No compatible source was found for this media."}”

PC也会出现这个错误，但播放正常

vue-video-player 版本：4.0.4

**Comment by surmon-china** [comment]
极有可能，微信不支持 webm，实测我的 IOS 11 微信 打开上面那个 `webm` 地址是无法播放的。

**Comment by wlinshicong** [comment]
只有ios10以上的safari才能播放啊
9的也播放不了

**Comment by surmon-china** [comment]
低版本 IOS 不支持，H5 Video 原生的兼容问题，无法解决。

**Comment by side9527** [comment]
视频源的问题，有的设备不支持html5，有的不支持flash

playerOptions: {
        autoplay: false, // 自动播放
        controls: true, // 是否显示控制栏
        techOrder: ['flash', 'html5'], // 兼容顺序
        sourceOrder: true, // 
        flash: { hls: { withCredentials: false } },
        html5: { hls: { withCredentials: false } },
        sources: [{ // 流配置，数组形式，会根据兼容顺序自动切换
          type: 'rtmp/mp4',
          src: 'rtmp://184.72.239.149/vod/&mp4:BigBuckBunny_115k.mov'
        }, {
          withCredentials: false,
          type: 'application/x-mpegURL',
          src: 'http://playertest.longtailvideo.com/adaptive/bipbop/gear4/prog_index.m3u8'
        }],
        poster: "/static/img/no_data.png", // 播放器默认图片
        // controlBar: { // 配置控制栏
        //   timeDivider: false, // 时间分割线
        //   durationDisplay: false, // 总时间
        //   progressControl: true, // 进度条
        //   customControlSpacer: true, // 未知
        //   fullscreenToggle: true // 全屏
        // },
      }
转自https://savokiss.com/tech/web-live-tech-with-vue.html
