### ISSUE TITLE
‘volume’ 不生效问题。

### ISSUE THREAD

**Issue by richaryau** [surmon-china/vue-video-player#92]
volume 这个选项，一直不生效的问题，请问如何解决？

        playerOptions: {
              // component options
              start: 0,
              // playsinline: true,
              // videojs options
              muted: false,
              language: 'zh-CN',
              playbackRates: [0.5, 1.0, 1.5, 2.0],
              sources: [{
                  type: "video/mp4",
                  src: "",
              }],
              poster: "",
              loop: false,
              autoplay: true,
              fluid: false,
              height:540,
             volume:0.5,
        },

加入'volume:0.5'后，加载视频时，音量依旧是100%。

**Comment by surmon-china** [comment]
不支持。

http://docs.videojs.com/docs/api/player.html#Methodsvolume

https://stackoverflow.com/questions/17585208/how-to-initially-mute-videos
