### ISSUE TITLE
VIDEOJS: ERROR: The "flash" tech is undefined. Skipped browser support check for that tech.

### ISSUE THREAD

**Issue by dqj** [surmon-china/vue-video-player#95]
When reading rtmp streaming file, the chrome's console reports the error message. Here is the option of player:
` playerOptions: {
        sources: [{
          type: "rtmp/mp4",
          src:'rtmp://localhost:1935/live/test&mp4:/tmp/rec/test.mp4'
       }],
        techOrder: ['flash', "html5"],
        autoplay: true,
        controls: true
      }`

**Comment by dqj** [comment]
import video

**Comment by greenpdx** [comment]
How do you import it?  
In my component, I tried to import it as a component, but that did not work.  Which file and how do you import it?

**Comment by surmon-china** [comment]
1. update `vue-video-player`to v5.0.0

2. remove `node_modules/videojs-*`

3. `npm i videojs-*`

**Comment by justahunzi** [comment]
npm i -D videojs-flash  babel-polyfill@6.26.0

**Comment by greenpdx** [comment]
I am using video.js 7.4 I have not tested it with flash yet, To get flash working just add a new tech. 
But adding buttons on the control panel is not easy.

**Comment by chenruiuestc** [comment]
> npm i -D videojs-flash babel-polyfill@6.26.0
> 尝试很多方法 发现安装了 babel-polyfill就可以正常使用了 ~~~

感谢！
