### ISSUE TITLE
demo中存在多个视频

### ISSUE THREAD

**Issue by kukujbb** [surmon-china/vue-video-player#96]
如何做到当我播放第二个视频的时候，第一个视频停止播放？？

**Comment by surmon-china** [comment]
监听第二个视频的 `play` 事件，事件发生时执行第一个视频的实例的 `stop` 方法。

**Comment by ee07b577** [comment]
如果demo中有很多个视频呢，比如10个。
在播放其中某个视频的时候，如何停止其他的视频实例？ref 循环吗？

**Comment by surmon-china** [comment]
@ee07b577 这就是个很简单的业务问题啊，有很多很多种方法能做到，你可以用组件容器包装所有 player，也可以统一绑定一样的 ref 属性，这样就能得到一个数组形式的 player 集合，然后各种循环操作就可以了。

**Comment by lishuliang28** [comment]
视频列表，为什么手动调用play的视频可以通过pause.停止。通过视频上控件开始的，调用pause不能停止啊
