### ISSUE TITLE
How to play youtube or vimeo video using vue-video-player module 

### ISSUE THREAD

**Issue by santoshshinde2012** [surmon-china/vue-video-player#97]
Please let me know any sample or way to play youtube or vimeo video using vue-video-player module .

I have tried to include videojs-youtube or videojs-vimeo, but its not work for me.

Thanks.

**Comment by surmon-china** [comment]
https://github.com/videojs/videojs-vimeo/issues/118
https://github.com/videojs/videojs-youtube/issues/465

`videojs 5`
https://github.com/surmon-china/vue-video-player/tree/v3.1.4

**Comment by viclafouch** [comment]
There is no example... Please give us example with YouTube or vimeo..

**Comment by pjconnect** [comment]
Browse 1h to find out, anyways. 
how to add any plugin:
https://github.com/surmon-china/vue-video-player/tree/v3.1.4

Basically,
```
//install via npm
require('videojs-youtube'); // add any plugin first and then
import { videoPlayer } from "vue-video-player";

//for youtube options be like,
playerOptions: {
 fluid: true,
 techOrder: [ 'youtube'],
 sources: [{
        type: "video/youtube",
         src: "https://www.youtube.com/watch?v=sLJwJ-phroc"
         }],
         poster: "/static/img/backgrounds/feature-video.jpg"
   }
```
