### ISSUE TITLE
Uncaught TypeError: window.setTimeout

### ISSUE THREAD

**Issue by chuangtim** [surmon-china/vue-video-player#98]
got a error when import vue-video-player in vue2.4.2

`Uncaught TypeError: window.setTimeout is not a function in video.cjs.js `

**Comment by surmon-china** [comment]
Show me the code detail please.

**Comment by surmon-china** [comment]
update `vue-video-player` to v5.0.0

**Comment by Wengjianhua** [comment]
I use the version v.5.0.2 but get the same error
ps: I use component global by Vue.use(VueVideoPlayer)

**Comment by bigbigJ** [comment]
nuxt  也报了这个错误 不知道如何解决
![image](https://user-images.githubusercontent.com/28619075/51166300-f217dd00-18dd-11e9-9588-84df643861fa.png)

**Comment by bigbigJ** [comment]
版本也是5.0.0  按照了你nuxt的方法写的  报了window.setTimeout is not a function

**Comment by bigbigJ** [comment]
到这一步就会报错
![image](https://user-images.githubusercontent.com/28619075/51166609-14f6c100-18df-11e9-9a62-212737d1461a.png)

**Comment by bigbigJ** [comment]
我查到是video.js 里的 延时调用报错，但不知道原因 也不知道如何解决
![image](https://user-images.githubusercontent.com/28619075/51166913-fcd37180-18df-11e9-8a87-30f988afccec.png)

**Comment by jsonpeter** [comment]
解决了没有？

**Comment by ailaiwuyou** [comment]
请问解决了没有
